Error 'HTTPConnectionPool(host='localhost', port=41262): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09bb7ec748>: Failed to establish a new connection: [Errno 111] Connection refused',))' happened on line 215    Tue May 21 16:31:41 2019
